### ISSUE TITLE
BeDialog关闭问题

### ISSUE THREAD

**Issue by yxsmile4ever** [beerui/BeerUi#20]
**Describe the bug**
BeDialog的beforeClose回调函数里面，返回false的时候，按正常逻辑，dialog是不能关闭的，但是实际项目中，他关闭了

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**REPL**
https://svelte.dev/repl/hello-world?version=3.45.0

**Comment by beerui** [comment]
未能复现，暂时关闭。
